### PR TITLE
Update Pico SDK v2.2.0

### LINKED ISSUE #35: Update PICO Loader to 2.2.0
There is a new version of the loader for PICO,

### PR DESCRIPTION
**Pull request by tiagozaccaro**
This commit updates assets extracted from Pico's OpenXR SDK to the latest version available from Pico, v2.2.0.

[Changelog from the official download page](https://developer-global.pico-interactive.com/sdk?deviceId=1&platformId=3&itemId=11)

Update：
- Supported OpenXR standard API 1.0.27.Add new XR_BD_controller_interaction extension.
- Optimize the OpenXR SDK directory.
- Please use the new version after OS 5.4.0.

closes #35

### CODE REVIEW

**Comment by BastiaanOlij** [comment]
Owh new drivers! Hope this release of the OS solves the Vulkan bug.

**Comment by tiagozaccaro** [comment]
Bastiaan, how can I test if it fixes the Vulkan issue?, because I tested on my PICO and it works normally.

**Comment by tiagozaccaro** [comment]
Can someone approve my pull request please?

**Review by BastiaanOlij — APPROVED** [review]
lgtm

**Pull request merged**
